language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.1

before install:
  - gem install bundler

script: script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
