language: ruby
cache: bundler
sudo: false
rvm:
- 2.3.1
matrix:
    include:
        - rvm: 2.3.1
          env: JEKYLL_VERSION=3
    fast_finish: true

before_script: bundle update
script: ./script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
