language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5
  - ruby-head

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle update

script: script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
