# Configuration
title: Frank Taillandier
description: Blog
url: https://frank.taillandier.me
repository: DirtyF/frank.taillandier.me
branch: master
baseurl: ""
permalink: pretty

kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false

sass:
  style: compressed

# seo-tag
logo: /assets/img/frank-taillandier.jpg
twitter:
  username: DirtyF
social:
  name: Frank Taillandier
  links:
    - https://github.com/DirtyF
    - https://twitter.com/DirtyF
    - https://keybase.io/dirtyf
    - http://lanyrd.com/profile/dirtyf/
    - http://www.last.fm/user/DirtyF

# reading_time
reading_time:
  words_per_minute: 180
  translations:
    about:
    minute: minute
    minutes: minutes

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      author: "Frank Taillandier"

include:
  - "_pages"

lsi: true

pagination:
  enabled: false
  per_page: 20
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - README.md
  - script
  - tmp
  - vendor

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-livereload
  - jekyll-mentions
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# About
author:
  name: Frank Taillandier
  email: frank@taillandier.me
  twitter: DirtyF

# External apps
analytics:
  google:
    tracking_id: UA-15560088-1
    site_verification: KhnXRq1e9zCBkD6X4vs_xwVc-6c-5an2vE7f0_-XMiE

disqus:
  shortname: franktaillandier
