# Configuration
title: Frank Taillandier
description: Articles & traductions
url: https://frank.taillandier.me
repository: DirtyF/frank.taillandier.me
branch: master
github:
  source:
    branch: master
baseurl: ""
permalink: /:year/:month/:day/:title/

sass:
  style: compressed

css_dir: assets/css

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

jekyll_tidy:
  compress_html: true
  ignore_env: development

# seo-tag
logo: /assets/img/frank-taillandier.jpg
twitter:
  username: FrankTldr
social:
  name: Frank Taillandier
  links:
    - http://lanyrd.com/profile/dirtyf/
    - http://www.last.fm/user/DirtyF
    - https://github.com/DirtyF
    - https://keybase.io/dirtyf
    - https://twitter.com/FrankTldr

cloudinary:
  cloud_name: jamstatic
  verbose: false
  presets:
    default:
      min_width: 320
      max_width: 864
      fallback_max_width: 720
      steps: 3
      sizes: "(min-width: 38rem) 36rem, (min-width: 32rem) 30rem, 90vw"

# reading_time
reading_time:
  words_per_minute: 180
  translations:
    about: environ
    minute: minute
    minutes: minutes

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      author: "Frank Taillandier"

include:
  - _headers
  - _pages
  - _redirects

pagination:
  enabled: false
  per_page: 20
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll_compose:
  auto_open: true

exclude:
  - .editorconfig
  - .stylelintrc.json
  - LICENSE
  - Rakefile
  - README.md
  - script
  - tmp

plugins:
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-redirect-from
  # jekyll-paginate-v2

# About
author:
  name: Frank Taillandier
  email: frank@taillandier.me
  twitter: FrankTldr
  avatar: https://github.com/DirtyF.png

# External apps
analytics:
  google:
    tracking_id: UA-15560088-1
    site_verification: KhnXRq1e9zCBkD6X4vs_xwVc-6c-5an2vE7f0_-XMiE

disqus:
  shortname: franktaillandier
