lsi: true
pwa:
  dest_js_directory: assets/js
  precache_recent_posts_num: 3
  precache_glob_directory: /
  precache_glob_patterns:
    - "assets/{js,css,fonts,favicons}/**/*.{js,css,eot,svg,ttf,woff2,woff}"
    - index.html
  precache_glob_ignores:
    - sw-register.js
