---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Articles
  create: all
  templates:
  - article
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year/:month:/:filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  - RUBY_VERSION=2.6.1
  - JEKYLL_GITHUB_TOKEN=7364b18499cc33e9a662f52cdcda42a55b602006
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --config _config.yml,_config_local.yml
    --drafts --unpublished --future --port 8080 --host 0.0.0.0 -d _site
