backend:
  name: github
  repo: DirtyF/frank.taillandier.me
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Twitter Card", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
